version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  tomcat:
    image: tomcat:10-jdk17
    container_name: tomcat-container
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - ./test.war:/usr/local/tomcat/webapps/test.war
    environment:
      TZ: Asia/Seoul

volumes:
  mysql_data:
